return {}

-- return {
--   {
--     'abecodes/tabout.nvim',
--     lazy = true,
--     config = function()
--         require("elaube.tabout")
--     end,
--     dependencies = { -- These are optional
--       "nvim-treesitter/nvim-treesitter",
--       "L3MON4D3/LuaSnip",
--       "hrsh7th/nvim-cmp"
--     },
--     after = { "nvim-treesitter", "LuaSnip", "nvim-cmp" },
--     opt = true,  -- Set this to true if the plugin is optional
--     event = 'InsertCharPre', -- Set the event to 'InsertCharPre' for better compatibility
--     priority = 1000,
--   },
--   {
--     "L3MON4D3/LuaSnip",
--     keys = function()
--       -- Disable default tab keybinding in LuaSnip
--       return {}
--     end,
--   },
-- }
